---
title: "Resumo"
output: html_document
date: "2022-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
A base de dados traz as informações sobre a demanda, vendas, investimentos em marketing em diversas mídias de uma indústria de telecomunicações chinesa.
A granularidade está no formato mensal e possui um período compreendido entre Jan/2010 a Fev/2017.

```{r}
#instalando pacotes
# install.packages("readxl")
# install.packages("lubridate")
library(lubridate)
library(readxl)
library(ggplot2)

##Transformando a data em classes diferentes
dados_mes<-read_excel("dados_mensais.xlsx")
dados_mes<-as.data.frame(dados_mes)
dados_mes$data_data<-format(as.Date(dados_mes$data), "%Y-%m")
typeof(dados_mes$data_data)
dados_mes$data_cor<-lubridate::ym(dados_mes$data_data)
dados_mes$data_fac<-as.factor(dados_mes$data_data)
head(dados_mes)

str(dados_mes)
install.packages('tsibble')
library(tsibble)
head(dados_mes)
library(tidyverse)

```

```{r}

#grafico da demanda
ggplot(data=dados_mes, aes(x=data_cor,y=m_demand)) +
  geom_line() + xlab("Período") + ylab("Demanda")


```


```{r}
#install.packages('feasts')
#install.packages('forecast')
library(feasts)
library(tidyverse)
library(tsibble)
library(forecast)
library(tsibble)
library(dplyr)
library(ggplot2)
#install.packages('tsibbledata')
library(tsibbledata)


str(dados_mes)
```

```{r}
#Preparando dados para criar grafico da demanda por ano

dados_mes %>%
  mutate(Month = tsibble::yearmonth(anomes)) %>%
  as_tsibble(index = Month) %>%
  dplyr::select(m_demand) -> demanda_tbl

head(demanda_tbl)
```



```{}
#Tranformando demanda em série temporal
str(demanda_tbl)
demanda_tbl_ts<-ts(demanda_tbl, frequency=12, start=c(2010,1))
str(demanda_tbl_ts)


```

```{r}
#Transformando toda base em série temporal
str(dados_mes)
dados_mes_ts<-ts(dados_mes, frequency=12, start=c(2010,1))
str(dados_mes_ts)
head(dados_mes_ts)

```